### ISSUE TITLE
Can not figure out how to add and env_keep line to an included file.

### ISSUE THREAD

**Issue by djibi2** [saltstack-formulas/sudoers-formula#32]
I have file that I'm trying to include.  The non-salt version looks like this:

```
jenkins` ALL=NOPASSWD: /usr/sbin/cowbuilder, /usr/sbin/chroot, /usr/bin/pbuilder
Defaults env_keep+="DEB_* DIST ARCH ADT BUILDBRANCHSTR APPVERSIONSTR  DEB_KEEP_BUILD_ENV"
```
I have figured out how to write the first line in a pillar, but can get the syntax right for the `env_keep+=` line.  Does anyone have any suggestions?

Currently I am trying a pillar like this:

```
sudoers:
  includedir: /etc/sudoers.d
  included_files:
    /etc/sudoers.d/91-jenkins:
      users:
        jenkins:
          - 'ALL=NOPASSWD: /usr/sbin/cowbuilder'
          - 'All=NOPASSWD: /usr/sbin/chroot'
          - 'ALL=NOPASSWD: /usr/bin/pbuilder'
      defaults:
        - env_keep='"DEB_* DIST ARCH ADT BUILDBRANCHSTR APPVERSIONSTR  DEB_KEEP_BUILD_ENV"'
```

I have tried several other versions of this, but get the error:

` Unable to manage file: Jinja variable 'list object' has no attribute 'get'
`
Without the "env_keep" line the pillar is processed properly.

**Comment by madrisan** [comment]
You should just add one line at a time:
```
sudoers:
  includedir: /etc/sudoers.d
  included_files:
    /etc/sudoers.d/91-jenkins:
      users:
        jenkins:
          - 'ALL=NOPASSWD: /usr/sbin/cowbuilder'
          - 'All=NOPASSWD: /usr/sbin/chroot'
          - 'ALL=NOPASSWD: /usr/bin/pbuilder'
      defaults:
        generic:
          - env_keep += "DEB_*"
          - env_keep += "DIST"
          - env_keep += "ARCH"
          - env_keep += "ADT"
          - env_keep += "BUILDBRANCHSTR"
          - env_keep += "APPVERSIONSTR"
          - env_keep += "DEB_KEEP_BUILD_ENV"      
```
