### ISSUE TITLE
error after upgrading to 2017 version of master

### ISSUE THREAD

**Issue by martinadolfi** [saltstack-formulas/sudoers-formula#35]
After upgrading salt-master to 2017, this formula keeps getting this error, at least on ubuntu:
```yaml
 ----------
          ID: /etc/sudoers
    Function: file.managed
      Result: False
     Comment: Failed to commit change: [Errno 2] No such file or directory: /tmp/__salt.tmp.cboCne
     Started: 23:51:11.292604
    Duration: 1441.796 ms
     Changes:
              ----------
              diff:
                  Replace text file with binary file
----------
```
