### ISSUE TITLE
Error using sudoers.included

### ISSUE THREAD

**Issue by brandentimm** [saltstack-formulas/sudoers-formula#6]
I am experiencing errors with the sudoers.included state related to the 'sudoers' variable in the /etc/sudoers template.  Here is my configuration:

In top.sls, sudoers is applied globally, and sudoers.included is applied to the host experiencing the error:
top.sls

``` yaml
base:
  '*':
    - sudoers
  'myhost':
    - sudoers.included
```

The pillar data for myhost is as follows:

``` yaml
sudoers:
  groups:
    itops: 'ALL=(ALL) ALL'
    sudo: 'ALL=(ALL) ALL'
  includedir: /etc/sudoers.d
  included_files:
    /etc/sudoers.d/git-salt:
      - users:
        - git: 'ALL= /usr/bin/salt-call'
```

However when salt is called, I receive the following error:

``` shell
          ID: /etc/sudoers.d/git-salt
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'list object' has no attribute 'get'; line 18

              ---
              [...]
                  {%- set users = sudoers.get('users', {}) %}
                  {%- set groups = sudoers.get('groups', {}) %}
                {%- endif %}
                {%- set includedir = sudoers.get('includedir', '/etc/sudoers.d') -%}
              {%- else %}
                {%- set defaults = sudoers.get('defaults', []) %}    <======================
                {%- set users = sudoers.get('users', {}) %}
                {%- set groups = sudoers.get('groups', {}) %}
                {%- set includedir = sudoers.get('includedir', None) %}
              {%- endif %}
              {%- set aliases = sudoers.get('aliases', {}) %}
              [...]
              ---
```

From looking at the code, it seems that indeed sudoers is not initialized if the file is included, which it is from sudoers.included.  sudoers.included does initialize sudoers from pillar, but I'm not sure how or if the context gets passed between the included file.

**Comment by vachaspativ** [comment]
+1
Very true, i have the same issue when using the sudoers.included

**Comment by gravyboat** [comment]
Hmm, I'm surprised this is still an issue (I actually don't even remember this one being opened last year sadly). @nmadhok Do you know who is familiar enough with this formula to do a quick fix? The contributors list is pretty sparse.

**Comment by nmadhok** [comment]
@carlosperello or @aboe76 May be able to provide a fix for this.

**Comment by vachaspativ** [comment]
Carlos or Niels, can you please let us know if there are any updates.
thanks.

**Comment by aboe76** [comment]
@vachaspativ 

Strange I run the same sudoers formula on my own machines, archlinux / opensuse / debian 

and I have this configuration:
```yaml
sudoers:
  users:
    root:
      - 'ALL=(ALL) ALL'
  defaults:
    generic:
      - env_reset
      - always_set_home
      - mail_no_perms
      - set_home
      - tty_tickets
      - mail_badpass
      - secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - editor=/usr/bin/vim
    user_list:
      aboe: '!requiretty'
    runas_list:
      root: '!set_logname'
  includedir: /etc/sudoers.d
  included_files:
    /etc/sudoers.d/10_XXXXXXXX:
      users:
        XXXXXXXX:
          - 'ALL=(ALL) NOPASSWD: ALL'
          - 'ALL = NOPASSWD: /usr/bin/build'
          - 'ALL = NOPASSWD: /usr/bin/osc'
```

And I don't see this problem,

**Comment by aboe76** [comment]
@vachaspativ update, 
even with this top.sls I don't see the issue you report:
```yaml
base:
  '*':
    - users
    - sudoers
    - sudoers.included
    - logrotate
    - openssh
    - openssh.client
    - openssh.config
    - vim.salt
    - vim.jinja
    - vim.repeat
    - salt.minion
    - haveged
  'example.home.lan':
    - sudoers.included
```

running state.highstate on example.home.lan is without issues.
